### PR TITLE
Make logo clickable

### PR DESCRIPTION
**Pull request by Kajeczko**
Issue #6 
Additional changes stated in commits.
cardstack/style.css & cardstack/functions.php LF and CRLF line endings conflict

### CODE REVIEW

**Comment by owoc** [comment]
This needs to be deployed on staging before merge. Please respond to my email so I can grant you access.

**Comment by Kajeczko** [comment]
done

**Review by owoc — CHANGES_REQUESTED** [review]
Huge 2000-line change in style.css makes this too hard to review. If you consider line endings a problem, fix them in a seprate commit.

**Comment by owoc** [comment]
N.b. I merged the first of 3 commits in this PR. Please amend the second so the changes to styles.css are easier to review.

**Comment by Kajeczko** [comment]
done by altering commits, for this I will ignore CRLF

**Comment by owoc** [comment]
Applied to master via 2 merge commits and a separate commit with the gitignore change. Closing.

**Pull request closed without merging**
